
version: "3.8"

networks:
    api-network:
        driver: bridge

services:
    rest-api:        
        image: qiswap/rest-api:latest                
        restart: always
        container_name: qiswap-rest-api
        volumes:
            - ../utils:/usr/src/utils 
        build:
            context: ../rest-api/
        networks:
            - api-network            
        
    graphql-api:        
        image: qiswap/graphql-api:latest                
        restart: always
        container_name: qiswap-graphql-api
        volumes:
            - ../utils:/usr/src/utils 
        build:
            context: ../graphql-api/
        networks:
            - api-network            

    nginx:        
        restart: always
        container_name: qiswap-proxy
        image: nginx:latest
        volumes:
            - ../homepage:/var/www/homepage/
            - ../nginx/conf.d:/etc/nginx/conf.d
            - ../nginx/certbot/conf:/etc/letsencrypt
            - ../nginx/certbot/data:/var/www/certbot
            - ../nginx/dhparam:/etc/ssl/certs
        ports:
            - 80:80
            - 443:443
        networks:
            - api-network            

    certbot:
        image: certbot/certbot:latest
        command: certonly --webroot --webroot-path=/var/www/certbot --email alejo@qtum.info --agree-tos --no-eff-email --force-renewal -d testnet-graph.qiswap.com 
        volumes:
            - ../nginx/certbot/conf:/etc/letsencrypt
            - ../nginx/certbot/logs:/var/log/letsencrypt
            - ../nginx/certbot/data:/var/www/certbot
            - ../homepage:/var/www/homepage/
