
version: "3.8"
services:
    rest-api:        
        restart: always
        container_name: qiswap-rest-api
        volumes:
            - ../utils:/usr/src/utils 
        build:
            context: ../rest-api/
        image: qiswap/rest-api:latest                
        
    graphql-api:        
        restart: always
        container_name: qiswap-graphql-api
        volumes:
            - ../utils:/usr/src/utils 
        build:
            context: ../graphql-api/
        image: qiswap/graphql-api:latest                

    nginx:        
        restart: always
        container_name: qiswap-proxy
        build:
            context: ../nginx            
        image: qiswap/proxyserver:latest
        ports:
            - "80:80"
        volumes:
            - ../homepage:/var/www/homepage/
