baseURL = "http://testnet-api.qiswap.com/"
languageCode = "en-us"
title = "QiSWAP testnet API"
Paginate = 1000
googleAnalytics = ""
theme = "showcase"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS"]

# this setting should always be set to false, otherwise it will break the section navigation bar
pluralizelisttitles = false

[params]
  author = "QiSWAP"
  description = "QiSWAP API Home Page"
  message = ""
  hideAutoMenu = true
  
  # Pagination options
  paginate = 3
  multipage = false

[[menu.main]]
  name = "HOME"
  url = ""

[social]
  facebook = "https://facebook.com"
  twitter = "https://twitter.com"